import { Navbar } from '@/components/navbar';
import { Toaster } from '@/components/ui/sonner';
import { ClientAuthProvider } from '@/components/providers/auth-provider';
import { ChatProvider } from '@/lib/chat/context';
import { getCurrentUser } from '@/lib/auth/server-utils';
import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const initialUser = await getCurrentUser();

  return (
    <html lang="fr">
      <body
        className="antialiased relative"
      >
        <ClientAuthProvider initialUser={initialUser}>
          <ChatProvider>
            <Navbar className="fixed top-0 w-full h-fit" />
            {children}
            <Toaster />
          </ChatProvider>
        </ClientAuthProvider>
      </body>
    </html>
  );
}
