import { NavBar } from '@/components/navbar';
import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';
import { AuthProvider } from '@/lib/auth/context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return <html lang="fr">
    <body
      className={`antialiased`}
    >
    <AuthProvider>
      <NavBar />
      {children}
    </AuthProvider>
    </body>
  </html>;
}
