services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db-test:
    image: postgres:17
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - db_test_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  smtp:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
  db_test_data: